name: Manhunt
version: '${project.version}'
main: com.optivat.manhunt.Manhunt
api-version: 1.16
authors: [ Optivat ]
description: A speedrunner(s) has to beat the game while hunter(s) have to kill them.
commands:
  speedrunner:
    description: Used to add or remove speedrunners.
    permission: manhunt.speedrunner
    aliases: [runner, speedrunners]
